// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(BaharSitesiDbContext))]
    [Migration("20231223152543_aidat_Guncel")]
    partial class aidat_Guncel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Aidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Aidats");
                });

            modelBuilder.Entity("WebApplication1.Models.Daire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Blok")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DaireNo")
                        .HasColumnType("int");

                    b.Property<int>("Kat")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Daires");
                });

            modelBuilder.Entity("WebApplication1.Models.DaireAidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AidatId")
                        .HasColumnType("int");

                    b.Property<int>("DaireId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ÖdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ÖdenenTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DaireId");

                    b.ToTable("DaireAidats");
                });

            modelBuilder.Entity("WebApplication1.Models.EvSahipleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DaireId")
                        .HasColumnType("int");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sorumlu")
                        .HasColumnType("bit");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DaireId");

                    b.ToTable("EvSahipleris");
                });

            modelBuilder.Entity("WebApplication1.Models.DaireAidat", b =>
                {
                    b.HasOne("WebApplication1.Models.Daire", "Daire")
                        .WithMany()
                        .HasForeignKey("DaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Daire");
                });

            modelBuilder.Entity("WebApplication1.Models.EvSahipleri", b =>
                {
                    b.HasOne("WebApplication1.Models.Daire", "Daire")
                        .WithMany("EvSahipleris")
                        .HasForeignKey("DaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Daire");
                });

            modelBuilder.Entity("WebApplication1.Models.Daire", b =>
                {
                    b.Navigation("EvSahipleris");
                });
#pragma warning restore 612, 618
        }
    }
}
